AWSTemplateFormatVersion: '2010-09-09'
Description: Start/Stop EC2 instance (Mon-Fri 8AM-5PM AEST)

Parameters:
  InstanceId:
    Type: String
    Default: i-0d3d9b23b4216c292
    Description: EC2 instance to schedule

Resources:
  StartEC2LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess

  StartEC2Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt StartEC2LambdaRole.Arn
      Runtime: python3.9
      Timeout: 30
      Code:
        ZipFile: |
          import boto3
          import os
          def handler(event, context):
              ec2 = boto3.client('ec2')
              instance_id = os.environ['INSTANCE_ID']
              if event['action'] == 'start':
                  ec2.start_instances(InstanceIds=[instance_id])
              elif event['action'] == 'stop':
                  ec2.stop_instances(InstanceIds=[instance_id])
              return 'OK'
      Environment:
        Variables:
          INSTANCE_ID: !Ref InstanceId

  StartRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 22 ? * MON-FRI *)   # 08:00 AEST = 22:00 UTC previous day
      State: ENABLED
      Targets:
        - Arn: !GetAtt StartEC2Lambda.Arn
          Id: StartEC2
          Input: '{"action":"start"}'

  StopRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: cron(0 07 ? * MON-FRI *)   # 17:00 AEST = 07:00 UTC same day
      State: ENABLED
      Targets:
        - Arn: !GetAtt StartEC2Lambda.Arn
          Id: StopEC2
          Input: '{"action":"stop"}'

  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref StartEC2Lambda
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
